In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from IPython import display
plt.rcParams['figure.figsize'] = (13,11)
plt.rcParams['font.size'] = 28

In [9]:
halo8Mass = np.loadtxt("spMassHaloOnly_08.00_0.txt",skiprows=1)
halo8Loc = np.loadtxt("spLocHaloOnly_08.00_0.txt",skiprows=1)
halo8Ppf = np.loadtxt("spPPFHaloOnly_08.00_0.txt",skiprows=1)
halo8Pz = np.loadtxt("spPZHaloOnly_08.00_0.txt",skiprows=1)
halo8Z = np.loadtxt("spZHaloOnly_08.00_0.txt",skiprows=1)

prefix = './'
z = "8.0"; i = "0" 
totSPM = np.loadtxt(prefix + "totSM_z" + z + "-" + i +".txt")
ppfSPM = np.loadtxt(prefix + "pristSM_z" + z + "-" + i +".txt")
ppzSPM = np.loadtxt(prefix + "primordSM_z" + z + "-" + i +".txt")

In [10]:
totSPM

array([      0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,    7981.50493966,    1451.1827163 ,
          6530.32222336,   10883.87037227,    2902.3654326 ,
         10158.27901412,    3627.95679076,   10883.87037227,
          2176.77407445,    7255.91358151,   17414.19259563,
         27572.47160974,  120448.16545309,   54419.35186133,
          3627.95679076,   11931.94677849,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,

In [11]:
bins    = np.logspace(-10, 0, 51) # Log bins for histogram data 
psm     = np.zeros(len(bins)-1) # Pristine Stellar mass in that bin
tsm     = np.zeros(len(bins)-1) # total mass
primsm  = np.zeros(len(bins)-1) # Primordial stellar mass
for indx2,j in enumerate(bins):
    if indx2 < len(bins)-1 :
        cond = (halo8Z >= j) & (halo8Z < bins[indx2+1]) # This selects for sp's in the bin
        psm[indx2] = np.sum(halo8Ppf[cond] * halo8Mass[cond]) # Pop III
        tsm[indx2] = np.sum(halo8Mass[cond]) # Total star particle mass in this bin
        primsm[indx2] = np.sum((1.0-halo8Ppf[cond]) * 
                                   (halo8Pz[cond] / (halo8Z[cond])) * halo8Mass[cond]) # Pz and Z are both solar

pristMass   = np.sum(psm)
totMass     = np.sum(tsm)
primordMass = np.sum(primsm)


In [12]:
tsm

array([      0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,    7981.50493966,    1451.1827163 ,
          6530.32222336,   10883.87037227,    2902.3654326 ,
         10158.27901412,    3627.95679076,   10883.87037227,
          2176.77407445,    7255.91358151,   17414.19259563,
         27572.47160974,  120448.16545309,   54419.35186133,
          3627.95679076,   11931.94677849,       0.        ,
             0.        ,       0.        ,       0.        ,
             0.        ,

In [13]:
halo5Mass = np.loadtxt("spMassHaloOnly_05.00_2562828.txt",skiprows=1)
halo5Loc = np.loadtxt("spLocHaloOnly_05.00_2562828.txt",skiprows=1)
halo5Ppf = np.loadtxt("spPPFHaloOnly_05.00_2562828.txt",skiprows=1)
halo5Pz = np.loadtxt("spPZHaloOnly_05.00_2562828.txt",skiprows=1)
halo5Z = np.loadtxt("spZHaloOnly_05.00_2562828.txt",skiprows=1)

prefix = './'
z = "5.0"; i = "2562828" 
totSPM = np.loadtxt(prefix + "totSM_z" + z + "-" + i +".txt")
ppfSPM = np.loadtxt(prefix + "pristSM_z" + z + "-" + i +".txt")
ppzSPM = np.loadtxt(prefix + "primordSM_z" + z + "-" + i +".txt")

In [32]:
bins    = np.logspace(-10, 0, 51) # Log bins for histogram data 
psm     = np.zeros(len(bins)-1) # Pristine Stellar mass in that bin
tsm     = np.zeros(len(bins)-1) # total mass
primsm  = np.zeros(len(bins)-1) # Primordial stellar mass
for indx2,j in enumerate(bins):
    if indx2 < len(bins)-1 :
        cond = (halo5Z >= j) & (halo5Z < bins[indx2+1]) # This selects for sp's in the bin
        psm[indx2] = np.sum(halo5Ppf[cond] * halo5Mass[cond]) # Pop III
        tsm[indx2] = np.sum(halo5Mass[cond]) # Total star particle mass in this bin
        primsm[indx2] = np.sum((1.0-halo5Ppf[cond]) * 
                                   (halo5Pz[cond] / (halo5Z[cond])) * halo5Mass[cond])
        print("%.2e, %.2e -> %.2e"%(j,bins[indx2+1],tsm[indx2]))


pristMass   = np.sum(psm)
totMass     = np.sum(tsm)
primordMass = np.sum(primsm)

1.00e-10, 1.58e-10 -> 0.00e+00
1.58e-10, 2.51e-10 -> 0.00e+00
2.51e-10, 3.98e-10 -> 0.00e+00
3.98e-10, 6.31e-10 -> 0.00e+00
6.31e-10, 1.00e-09 -> 0.00e+00
1.00e-09, 1.58e-09 -> 0.00e+00
1.58e-09, 2.51e-09 -> 0.00e+00
2.51e-09, 3.98e-09 -> 0.00e+00
3.98e-09, 6.31e-09 -> 0.00e+00
6.31e-09, 1.00e-08 -> 0.00e+00
1.00e-08, 1.58e-08 -> 0.00e+00
1.58e-08, 2.51e-08 -> 0.00e+00
2.51e-08, 3.98e-08 -> 0.00e+00
3.98e-08, 6.31e-08 -> 0.00e+00
6.31e-08, 1.00e-07 -> 0.00e+00
1.00e-07, 1.58e-07 -> 0.00e+00
1.58e-07, 2.51e-07 -> 0.00e+00
2.51e-07, 3.98e-07 -> 0.00e+00
3.98e-07, 6.31e-07 -> 0.00e+00
6.31e-07, 1.00e-06 -> 0.00e+00
1.00e-06, 1.58e-06 -> 0.00e+00
1.58e-06, 2.51e-06 -> 0.00e+00
2.51e-06, 3.98e-06 -> 0.00e+00
3.98e-06, 6.31e-06 -> 0.00e+00
6.31e-06, 1.00e-05 -> 0.00e+00
1.00e-05, 1.58e-05 -> 0.00e+00
1.58e-05, 2.51e-05 -> 1.45e+03
2.51e-05, 3.98e-05 -> 5.80e+03
3.98e-05, 6.31e-05 -> 0.00e+00
6.31e-05, 1.00e-04 -> 2.18e+03
1.00e-04, 1.58e-04 -> 2.18e+03
1.58e-04, 2.51e-04 -> 1.45e+03
2.51e-04

In [35]:
halo5Mass[halo5Z > 0.1] # There should be two stars... 

array([], dtype=float64)

In [34]:
np.sum(halo5Mass[halo5Z > 0.063]) # THIS IS THE BUG... I should be totaling > 0.1 for this one

74816.53115158221

In [24]:
bins[1:51],tsm, totSPM

(array([  1.58489319e-10,   2.51188643e-10,   3.98107171e-10,
          6.30957344e-10,   1.00000000e-09,   1.58489319e-09,
          2.51188643e-09,   3.98107171e-09,   6.30957344e-09,
          1.00000000e-08,   1.58489319e-08,   2.51188643e-08,
          3.98107171e-08,   6.30957344e-08,   1.00000000e-07,
          1.58489319e-07,   2.51188643e-07,   3.98107171e-07,
          6.30957344e-07,   1.00000000e-06,   1.58489319e-06,
          2.51188643e-06,   3.98107171e-06,   6.30957344e-06,
          1.00000000e-05,   1.58489319e-05,   2.51188643e-05,
          3.98107171e-05,   6.30957344e-05,   1.00000000e-04,
          1.58489319e-04,   2.51188643e-04,   3.98107171e-04,
          6.30957344e-04,   1.00000000e-03,   1.58489319e-03,
          2.51188643e-03,   3.98107171e-03,   6.30957344e-03,
          1.00000000e-02,   1.58489319e-02,   2.51188643e-02,
          3.98107171e-02,   6.30957344e-02,   1.00000000e-01,
          1.58489319e-01,   2.51188643e-01,   3.98107171e-01,
        

In [36]:
len(halo5Mass)

4671